# Конфигурация анализа базиса спот-фьючерс

# Настройки синхронизации
sync:
  max_lag_ms: 5000              # Максимальный допустимый лаг между спот и фьючерс
  min_overlap_ratio: 0.8        # Минимальное перекрытие данных для анализа
  tolerance_ms: 100             # Толерантность синхронизации (мс)

# Временные настройки
time:
  tick_size_ms: 10              # Шаг агрегации в миллисекундах
  min_window_ms: 1000           # Минимальное окно для анализа
  max_window_ms: 60000          # Максимальное окно для анализа

# Настройки базиса
basis:
  max_basis_rel: 50.0           # Максимальный относительный базис (%)
  min_basis_rel: -50.0          # Минимальный относительный базис (%)
  min_price_threshold: 0.1      # Минимальная цена для валидации
  validate_crosses: true        # Валидация пересечений цен

# Настройки аномалий
anomaly:
  threshold: 2.0                # Порог для пометки аномалий (0-1)
  volatility_threshold: 0.95    # Процентиль для волатильности (0.95 = 95%)
  change_threshold: 0.95        # Процентиль для изменений (0.95 = 95%)
  score_weights:
    ma_deviation: 0.7           # Вес отклонения от MA
    volatility: 0.3             # Вес волатильности

# Скользящие средние
moving_averages:
  - 5                           # Короткое окно
  - 10                          # Среднее окно
  - 20                          # Длинное окно
  - 50                          # Очень длинное окно

# Настройки волатильности
volatility:
  window: 20                    # Окно для вычисления волатильности
  min_samples: 5                # Минимальное количество образцов
  outlier_threshold: 3.0        # Порог для выбросов (в стандартных отклонениях)

# Категоризация базиса
categorization:
  strong_contango: 5.0          # Сильный контанго (>5%)
  contango: 1.0                 # Контанго (1-5%)
  near_par: -1.0                # Около паритета (-1% до 1%)
  backwardation: -5.0           # Бэквардация (-1% до -5%)
  strong_backwardation: -5.0    # Сильный бэквардация (<-5%)

# Настройки агрегации
aggregation:
  group_by_exchange: true        # Группировка по биржам
  group_by_symbol: true          # Группировка по символам
  group_by_time: true            # Группировка по времени
  calculate_metrics: true        # Вычисление дополнительных метрик

# Настройки экспорта
export:
  save_raw_data: true            # Сохранять сырые данные
  save_aggregated: true          # Сохранять агрегированные данные
  save_summaries: true           # Сохранять сводки
  compression: "snappy"          # Сжатие данных
  batch_size: 10000              # Размер пакета для обработки

# Настройки логирования
logging:
  progress_interval: 1000        # Интервал логирования прогресса
  debug_level: false             # Включить детальное логирование
  save_logs: true                # Сохранять логи в файл
