# Конфигурация Scalping Strategy
project:
  name: "Scalping Strategy"
  version: "0.1.0"
  description: "Система детекции паттернов для скальпинга"

# Настройки детекторов
detectors:
  # D1: Liquidity Vacuum Break
  lvb_min_vacuum_size: 1000  # USDT
  lvb_vacuum_threshold: 0.7  # 70% исчезновения
  lvb_refill_threshold: 0.5  # 50% восстановления
  lvb_time_window: 1000      # мс
  
  # D2: Absorption Flip
  absorption_min_volume: 500  # USDT
  absorption_threshold: 0.6   # 60% поглощения
  
  # D3: Iceberg Fade
  iceberg_min_size: 2000      # USDT
  iceberg_fade_threshold: 0.8 # 80% затухания
  
  # D4: Stop Run Continuation
  stoprun_min_moves: 3        # минимальное количество движений
  stoprun_confidence: 0.7     # минимальная уверенность
  
  # D5: Stop Run Failure
  stoprun_failure_threshold: 0.6  # порог неудачи
  
  # D6: Book Imbalance
  imbalance_threshold: 0.3    # порог дисбаланса
  
  # D7: Spoof Pull Trap
  spoof_min_size: 1000       # минимальный размер спуфа
  spoof_pull_threshold: 0.7  # порог вытягивания
  
  # D8: Momentum Ignition
  momentum_min_volume: 3000   # минимальный объем
  momentum_threshold: 0.8     # порог импульса

# Настройки стратегии
strategy:
  entry_rules:
    min_confidence: 0.7       # минимальная уверенность для входа
    min_volume: 1000          # минимальный объем
    max_spread: 0.002         # максимальный спред (0.2%)
  
  exit_rules:
    stop_loss: true            # использовать stop loss
    take_profit: true          # использовать take profit
    trailing_stop: false       # trailing stop (пока отключен)

# Управление рисками
risk_management:
  stop_loss_pct: 2.0          # stop loss в процентах
  take_profit_pct: 4.0        # take profit в процентах
  max_position_size: 1.0      # максимальный размер позиции
  max_daily_loss: 5.0         # максимальный дневной убыток в %

# Размер позиции
position_sizing:
  max_size: 1.0               # максимальный размер позиции
  risk_per_trade: 0.02        # риск на сделку (2%)
  position_scaling: false      # масштабирование позиций

# Настройки экспорта
export:
  encoding: 'utf-8'
  separator: ','
  decimal_separator: '.'
  date_format: '%Y-%m-%d %H:%M:%S'
  formats: ['csv', 'tradingview', 'atas']

# Настройки ATAS
atas:
  marker_size: 'medium'
  color_scheme: 'default'
  time_format: 'HH:mm:ss'
