# Конфигурация блока 04: Синхронизация времени
sync_time:
  # Основные параметры синхронизации
  reference_exchange: "binance" # Биржа-эталон для синхронизации
  max_lag_seconds: 10 # Максимальный лаг между биржами в секундах
  correlation_threshold: 0.7 # Минимальная корреляция для валидной синхронизации
  
  # Параметры временных окон
  time_bucket_ms: 1000 # Размер временного бакета в миллисекундах
  min_data_points: 50 # Минимальное количество точек для анализа корреляции
  
  # Фильтрация данных
  min_data_coverage: 0.8 # Минимальное покрытие данных (80%)
  max_price_deviation: 0.05 # Максимальное отклонение цены (5%)
  
  # Валидация качества синхронизации
  min_alignment_score: 0.85 # Минимальный балл выравнивания
  max_timestamp_diff_ms: 100 # Максимальная разница временных меток
  
  # Обработка ошибок
  skip_invalid_exchanges: true # Пропускать биржи с ошибками синхронизации
  log_sync_errors: true # Логировать ошибки синхронизации
  
  # Производительность
  batch_size: 10000 # Размер пакета для обработки
  parallel_processing: false # Параллельная обработка (пока отключено)
  
  # Выходные данные
  save_sync_report: true # Сохранять отчет о синхронизации
  save_aligned_data: true # Сохранять выровненные данные
  
  # Логирование
  log_level: "INFO"
  log_progress: true # Логировать прогресс синхронизации
