# Конфигурация анализа ленты сделок

# Временные окна для анализа (в миллисекундах)
windows:
  short: 1000      # 1 секунда
  medium: 10000     # 10 секунд
  long: 60000       # 1 минута
  extra_long: 300000 # 5 минут

# Настройки агрессии
aggression:
  threshold: 0.6           # Порог для определения агрессивности
  min_trades_for_analysis: 10  # Минимальное количество сделок для анализа
  price_change_threshold: 0.001 # Минимальное изменение цены для агрессии

# Настройки объемов
volumes:
  min_trade_size: 0.1      # Минимальный размер сделки для анализа
  large_trade_multiplier: 2.0  # Множитель для определения крупных сделок
  volume_quantiles: [0.25, 0.5, 0.75, 0.9, 0.95, 0.99]  # Квантили объемов

# Настройки метрик
metrics:
  vwap_window: 20          # Окно для VWAP
  volatility_window: 20     # Окно для волатильности
  imbalance_window: 100     # Окно для дисбаланса торгового потока
  
# Настройки экспорта
export:
  save_raw_data: true       # Сохранять сырые данные
  save_aggregated: true     # Сохранять агрегированные данные
  compression: "snappy"     # Сжатие данных
  batch_size: 10000         # Размер пакета для обработки

# Настройки логирования
logging:
  progress_interval: 3      # Интервал логирования прогресса (биржи)
  debug_level: false        # Включить детальное логирование
